# Generated by Django 6.0.7 on 2026-08-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Цена за покупку"
            ),
        ),
    ]
