# Generated by Django 6.0.7 on 2026-08-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание нужного вам продукта",
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
