# Generated by Django 6.0.7 on 2026-08-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Если отмечено,будет виден в каталоге",
                verbose_name="Опубликован",
            ),
        ),
    ]
