# Generated by Django 6.0.7 on 2026-08-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at", "-updated_at", "category", "price"],
                "permissions": [
                    ("can_unpublish_product", "Может снимать продукты с публикации")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
