# Generated by Django 6.0.7 on 2026-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="URL-идентификатор (slug)",
            ),
        ),
    ]
