# Generated by Django 6.0.7 on 2026-08-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="URL-идентификатор (slug)"
            ),
        ),
    ]
